#!/usr/bin/env python3
"""
Solar neutrino nu-e scattering plots using the flavor-separated fluxes
generated by the solar-neutrino flux script.

Expected input CSV columns from the previous script:
    E_MeV
    total_dphi_dE
    nu_e_dphi_dE
    nu_mu_dphi_dE
    nu_tau_dphi_dE

The script produces:

1) cross_sections_plain.png
   Approximate total cross sections vs neutrino energy.

2) input_fluxes_by_flavor.png
   Input neutrino fluxes by flavor from the CSV.

3) angular_differential_cross_sections_nu_e.png
   dσ/dcosθ for ν_e e scattering at selected neutrino energies.

4) angular_differential_cross_sections_nu_x.png
   dσ/dcosθ for ν_μ,τ e scattering at selected neutrino energies.

5) convolved_rate_per_energy_bin_by_flavor.png
   Flux-convolved interaction-rate contribution per neutrino-energy bin
   for ν_e, ν_μ, ν_τ separately and summed.

6) convolved_angular_rate_by_flavor.png
   Flux-convolved angular rate dR/dcosθ for ν_e, ν_μ, ν_τ separately and summed.

7) convolved_angular_pdf_by_flavor.png
   Normalized angular distributions for ν_e, ν_μ, ν_τ and total.

8) summary.txt
   Integrated rates for one electron target.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# Constants
# ============================================================
M_E_MEV = 0.51099895
SIN2_THETA_W = 0.23126
GF_GEV = 1.1663787e-5
GEV2_TO_CM2 = 0.389379338e-27
FLUX_DIR= Path("./solar_neutrino_fluxes")

# ============================================================
# Approximate total cross sections
# sigma(E) = coeff * E(MeV) [cm^2]
# ============================================================
SIGMA_COEFF = {
    "nu_e": 9.20e-45,
    "anti_nu_e": 3.83e-45,
    "nu_x": 1.57e-45,       # nu_mu, nu_tau
    "anti_nu_x": 1.29e-45,
}


# ============================================================
# Weak couplings
# ============================================================
def couplings(channel: str) -> tuple[float, float]:
    s2w = SIN2_THETA_W
    if channel == "nu_e":
        return 0.5 + s2w, s2w
    if channel == "anti_nu_e":
        return s2w, 0.5 + s2w
    if channel == "nu_x":
        return -0.5 + s2w, s2w
    if channel == "anti_nu_x":
        return s2w, -0.5 + s2w
    raise ValueError(f"Unknown channel: {channel}")


# ============================================================
# I/O
# ============================================================
def read_flux_csv(path: Path) -> pd.DataFrame:
    """
    Read the CSV produced by the previous solar-neutrino flux script.

    Expected numeric columns:
      E_MeV
      total_dphi_dE
      nu_e_dphi_dE
      nu_mu_dphi_dE
      nu_tau_dphi_dE

    The function is robust against descriptive text rows at the top.
    """
    raw = pd.read_csv(path, dtype=str)

    wanted = ["E_MeV", "total_dphi_dE", "nu_e_dphi_dE", "nu_mu_dphi_dE", "nu_tau_dphi_dE"]
    missing = [c for c in wanted if c not in raw.columns]
    if missing:
        raise ValueError(
            "Missing required CSV columns: "
            + ", ".join(missing)
            + "\nAvailable columns are: "
            + ", ".join(raw.columns)
        )

    df = pd.DataFrame()
    for col in wanted:
        df[col] = pd.to_numeric(raw[col], errors="coerce")

    df = df.dropna()
    df = df[df["E_MeV"] > 0].copy()
    df = df.sort_values("E_MeV").reset_index(drop=True)

    if len(df) < 2:
        raise ValueError("Not enough valid numeric rows found in the CSV.")

    return df


# ============================================================
# Grid helpers
# ============================================================
def bin_widths_from_centers(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    dx = np.empty_like(x)
    dx[1:-1] = 0.5 * (x[2:] - x[:-2])
    dx[0] = x[1] - x[0]
    dx[-1] = x[-1] - x[-2]
    return dx


# ============================================================
# Cross sections
# ============================================================
def sigma_total_approx(E_MeV: np.ndarray, channel: str = "nu_e") -> np.ndarray:
    return SIGMA_COEFF[channel] * np.asarray(E_MeV, dtype=float)


def Tmax(E_MeV: float) -> float:
    E = float(E_MeV)
    return 2.0 * E**2 / (M_E_MEV + 2.0 * E)


def Emin_from_T(T_MeV: np.ndarray) -> np.ndarray:
    T = np.asarray(T_MeV, dtype=float)
    return 0.5 * (T + np.sqrt(T**2 + 2.0 * M_E_MEV * T))


def dsigma_dT_sm(E_MeV: float, T_MeV: np.ndarray, channel: str = "nu_e") -> np.ndarray:
    """
    Tree-level Standard Model differential cross section dσ/dT.

    Returns:
        dσ/dT in cm^2 / MeV
    """
    E = float(E_MeV)
    T = np.asarray(T_MeV, dtype=float)

    gL, gR = couplings(channel)

    prefactor_gev = 2.0 * (GF_GEV ** 2) * (M_E_MEV * 1e-3) / np.pi
    prefactor = prefactor_gev * GEV2_TO_CM2 / 1000.0

    bracket = (
        gL**2
        + gR**2 * (1.0 - T / E) ** 2
        - gL * gR * (M_E_MEV * T) / (E**2)
    )

    out = prefactor * bracket
    out[(T < 0) | (T > Tmax(E))] = 0.0
    out[out < 0] = 0.0
    return out


# ============================================================
# Kinematics: T <-> cos(theta)
# ============================================================
def T_from_costh(E_MeV: float, costh: np.ndarray) -> np.ndarray:
    E = float(E_MeV)
    c = np.asarray(costh, dtype=float)
    num = 2.0 * M_E_MEV * E**2 * c**2
    den = (E + M_E_MEV)**2 - E**2 * c**2
    return num / den


def dT_dcosth(E_MeV: float, costh: np.ndarray) -> np.ndarray:
    E = float(E_MeV)
    c = np.asarray(costh, dtype=float)
    num = 4.0 * M_E_MEV * E**2 * (E + M_E_MEV)**2 * c
    den = ((E + M_E_MEV)**2 - E**2 * c**2) ** 2
    return num / den


def dsigma_dcosth_shape(E_MeV: float, costh: np.ndarray, channel: str = "nu_e") -> np.ndarray:
    c = np.asarray(costh, dtype=float)
    out = np.zeros_like(c)

    mask = (c >= 0.0) & (c <= 1.0)
    if not np.any(mask):
        return out

    T = T_from_costh(E_MeV, c[mask])
    jac = dT_dcosth(E_MeV, c[mask])
    out[mask] = dsigma_dT_sm(E_MeV, T, channel=channel) * jac
    out[out < 0] = 0.0
    return out


def dsigma_dcosth_rescaled(E_MeV: float, costh: np.ndarray, channel: str = "nu_e") -> np.ndarray:
    """
    Use the SM angular shape, but rescale it so that the integral over cos(theta)
    matches the chosen approximate total cross section.
    """
    c = np.asarray(costh, dtype=float)
    shape = dsigma_dcosth_shape(E_MeV, c, channel=channel)
    integral = np.trapz(shape, c)
    sigma_target = sigma_total_approx(np.array([E_MeV]), channel=channel)[0]

    if integral <= 0:
        return np.zeros_like(c)
    return shape * (sigma_target / integral)


# ============================================================
# Flux convolutions
# ============================================================
def convolved_rate_per_bin(E_MeV: np.ndarray, flux: np.ndarray, channel: str) -> np.ndarray:
    """
    Rate in each neutrino-energy bin for one electron target:
        rate_bin(E_i) = phi(E_i) * sigma(E_i) * dE_i

    Units: s^-1 per electron per bin
    """
    dE = bin_widths_from_centers(E_MeV)
    sigma = sigma_total_approx(E_MeV, channel=channel)
    return flux * sigma * dE


def convolved_angular_rate(E_MeV: np.ndarray, flux: np.ndarray, costh: np.ndarray,
                           channel: str) -> np.ndarray:
    """
    dR/dcos(theta) = integral dE phi(E) dσ/dcos(theta)

    Units: s^-1 per electron
    """
    dE = bin_widths_from_centers(E_MeV)
    rate = np.zeros_like(costh, dtype=float)
    for E, phi, dEi in zip(E_MeV, flux, dE):
        rate += phi * dsigma_dcosth_rescaled(E, costh, channel=channel) * dEi
    return rate


# ============================================================
# Plotting
# ============================================================
def make_plots(df: pd.DataFrame, outdir: Path,
               angular_energies: list[float] | None = None) -> None:
    outdir.mkdir(parents=True, exist_ok=True)

    E = df["E_MeV"].to_numpy()
    flux_total = df["total_dphi_dE"].to_numpy()
    flux_nue = df["nu_e_dphi_dE"].to_numpy()
    flux_numu = df["nu_mu_dphi_dE"].to_numpy()
    flux_nutau = df["nu_tau_dphi_dE"].to_numpy()

    if angular_energies is None:
        angular_energies = [0.1, 0.3, 0.862, 1.0, 5.0, 10.0]
    angular_energies = [x for x in angular_energies if E.min() <= x <= E.max()]
    if not angular_energies:
        angular_energies = [float(np.median(E))]

    # --------------------------------------------------------
    # 1) Plain cross sections
    # --------------------------------------------------------
    plt.figure(figsize=(8, 5.5))
    for ch, label in [
        ("nu_e", r"$\nu_e e^- \to \nu_e e^-$"),
        ("anti_nu_e", r"$\bar{\nu}_e e^- \to \bar{\nu}_e e^-$"),
        ("nu_x", r"$\nu_{\mu,\tau} e^- \to \nu_{\mu,\tau} e^-$"),
        ("anti_nu_x", r"$\bar{\nu}_{\mu,\tau} e^- \to \bar{\nu}_{\mu,\tau} e^-$"),
    ]:
        plt.plot(E, sigma_total_approx(E, ch), linewidth=2, label=label)
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel(r"Neutrino energy $E_\nu$ [MeV]")
    plt.ylabel(r"Total cross section $\sigma(E_\nu)$ [cm$^2$]")
    plt.title(r"Approximate $\nu$-e total cross sections")
    plt.grid(True, which="both", alpha=0.3)
    plt.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(outdir / "cross_sections_plain.png", dpi=180)
    plt.close()

    # --------------------------------------------------------
    # 2) Input fluxes by flavor
    # --------------------------------------------------------
    plt.figure(figsize=(8, 5.5))
    plt.plot(E, flux_total, linewidth=2.5, linestyle="--", label="total source")
    plt.plot(E, flux_nue, linewidth=2, label=r"$\nu_e$")
    plt.plot(E, flux_numu, linewidth=2, label=r"$\nu_\mu$")
    plt.plot(E, flux_nutau, linewidth=2, label=r"$\nu_\tau$")
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel(r"Neutrino energy $E_\nu$ [MeV]")
    plt.ylabel(r"$d\Phi/dE_\nu$ [cm$^{-2}$ s$^{-1}$ MeV$^{-1}$]")
    plt.title("Input solar-neutrino fluxes by flavor")
    plt.grid(True, which="both", alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(outdir / "input_fluxes_by_flavor.png", dpi=180)
    plt.close()

    # --------------------------------------------------------
    # 3) Angular differential cross sections for nu_e
    # --------------------------------------------------------
    costh = np.linspace(0.0, 1.0, 1200)

    plt.figure(figsize=(8, 5.5))
    for Ei in angular_energies:
        dsdc = dsigma_dcosth_rescaled(Ei, costh, channel="nu_e")
        plt.plot(costh, dsdc, linewidth=2, label=fr"$E_\nu={Ei:g}$ MeV")
    plt.yscale("log")
    plt.xlabel(r"$\cos\theta_e$")
    plt.ylabel(r"$d\sigma/d\cos\theta_e$ [cm$^2$]")
    plt.title(r"Angular differential cross section for $\nu_e e^-$")
    plt.grid(True, which="both", alpha=0.3)
    plt.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(outdir / "angular_differential_cross_sections_nu_e.png", dpi=180)
    plt.close()

    # --------------------------------------------------------
    # 4) Angular differential cross sections for nu_x
    # --------------------------------------------------------
    plt.figure(figsize=(8, 5.5))
    for Ei in angular_energies:
        dsdc = dsigma_dcosth_rescaled(Ei, costh, channel="nu_x")
        plt.plot(costh, dsdc, linewidth=2, label=fr"$E_\nu={Ei:g}$ MeV")
    plt.yscale("log")
    plt.xlabel(r"$\cos\theta_e$")
    plt.ylabel(r"$d\sigma/d\cos\theta_e$ [cm$^2$]")
    plt.title(r"Angular differential cross section for $\nu_{\mu,\tau} e^-$")
    plt.grid(True, which="both", alpha=0.3)
    plt.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(outdir / "angular_differential_cross_sections_nu_x.png", dpi=180)
    plt.close()

    # --------------------------------------------------------
    # 5) Convolved rate per energy bin by flavor
    # --------------------------------------------------------
    rate_bin_nue = convolved_rate_per_bin(E, flux_nue, channel="nu_e")
    rate_bin_numu = convolved_rate_per_bin(E, flux_numu, channel="nu_x")
    rate_bin_nutau = convolved_rate_per_bin(E, flux_nutau, channel="nu_x")
    rate_bin_total = rate_bin_nue + rate_bin_numu + rate_bin_nutau

    plt.figure(figsize=(8, 5.5))
    plt.plot(E, rate_bin_nue, linewidth=2, label=r"$\nu_e$")
    plt.plot(E, rate_bin_numu, linewidth=2, label=r"$\nu_\mu$")
    plt.plot(E, rate_bin_nutau, linewidth=2, label=r"$\nu_\tau$")
    plt.plot(E, rate_bin_total, linewidth=2.5, linestyle="--", label="total")
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel(r"Neutrino energy $E_\nu$ [MeV]")
    plt.ylabel(r"Rate per bin [s$^{-1}$ per electron]")
    plt.title(r"Flux-convolved $\nu$-e interaction rate per energy bin")
    plt.grid(True, which="both", alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(outdir / "convolved_rate_per_energy_bin_by_flavor.png", dpi=180)
    plt.close()

    # --------------------------------------------------------
    # 6) Convolved angular rate by flavor
    # --------------------------------------------------------
    angular_rate_nue = convolved_angular_rate(E, flux_nue, costh, channel="nu_e")
    angular_rate_numu = convolved_angular_rate(E, flux_numu, costh, channel="nu_x")
    angular_rate_nutau = convolved_angular_rate(E, flux_nutau, costh, channel="nu_x")
    angular_rate_total = angular_rate_nue + angular_rate_numu + angular_rate_nutau

    plt.figure(figsize=(8, 5.5))
    plt.plot(costh, angular_rate_nue, linewidth=2, label=r"$\nu_e$")
    plt.plot(costh, angular_rate_numu, linewidth=2, label=r"$\nu_\mu$")
    plt.plot(costh, angular_rate_nutau, linewidth=2, label=r"$\nu_\tau$")
    plt.plot(costh, angular_rate_total, linewidth=2.5, linestyle="--", label="total")
    plt.yscale("log")
    plt.xlabel(r"$\cos\theta_e$")
    plt.ylabel(r"$dR/d\cos\theta_e$ [s$^{-1}$ per electron]")
    plt.title(r"Flux-convolved angular rate for one electron target")
    plt.grid(True, which="both", alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(outdir / "convolved_angular_rate_by_flavor.png", dpi=180)
    plt.close()

    # --------------------------------------------------------
    # 7) Convolved angular PDFs by flavor
    # --------------------------------------------------------
    def normalize_pdf(y: np.ndarray, x: np.ndarray) -> np.ndarray:
        norm = np.trapz(y, x)
        return y / norm if norm > 0 else y

    angular_pdf_nue = normalize_pdf(angular_rate_nue, costh)
    angular_pdf_numu = normalize_pdf(angular_rate_numu, costh)
    angular_pdf_nutau = normalize_pdf(angular_rate_nutau, costh)
    angular_pdf_total = normalize_pdf(angular_rate_total, costh)

    plt.figure(figsize=(8, 5.5))
    plt.plot(costh, angular_pdf_nue, linewidth=2, label=r"$\nu_e$")
    plt.plot(costh, angular_pdf_numu, linewidth=2, label=r"$\nu_\mu$")
    plt.plot(costh, angular_pdf_nutau, linewidth=2, label=r"$\nu_\tau$")
    plt.plot(costh, angular_pdf_total, linewidth=2.5, linestyle="--", label="total")
    plt.xlabel(r"$\cos\theta_e$")
    plt.ylabel("Normalized distribution")
    plt.title("Possible recoil directions by neutrino flavor")
    plt.grid(True, which="both", alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(outdir / "convolved_angular_pdf_by_flavor.png", dpi=180)
    plt.close()

    # --------------------------------------------------------
    # 8) Summary text
    # --------------------------------------------------------
    total_rate_nue = np.sum(rate_bin_nue)
    total_rate_numu = np.sum(rate_bin_numu)
    total_rate_nutau = np.sum(rate_bin_nutau)
    total_rate = np.sum(rate_bin_total)

    with open(outdir / "summary.txt", "w", encoding="utf-8") as f:
        f.write("Solar nu-e scattering summary for a single electron target\n")
        f.write("\n")
        f.write(f"Energy range in input CSV: {E.min():.6g} to {E.max():.6g} MeV\n")
        f.write("\n")
        f.write("Integrated interaction rates:\n")
        f.write(f"  nu_e   : {total_rate_nue:.6e} s^-1 per electron\n")
        f.write(f"  nu_mu  : {total_rate_numu:.6e} s^-1 per electron\n")
        f.write(f"  nu_tau : {total_rate_nutau:.6e} s^-1 per electron\n")
        f.write(f"  total  : {total_rate:.6e} s^-1 per electron\n")
        f.write("\n")
        f.write("Equivalent per year:\n")
        f.write(f"  nu_e   : {total_rate_nue * 365.25 * 24 * 3600:.6e} year^-1 per electron\n")
        f.write(f"  nu_mu  : {total_rate_numu * 365.25 * 24 * 3600:.6e} year^-1 per electron\n")
        f.write(f"  nu_tau : {total_rate_nutau * 365.25 * 24 * 3600:.6e} year^-1 per electron\n")
        f.write(f"  total  : {total_rate * 365.25 * 24 * 3600:.6e} year^-1 per electron\n")


# ============================================================
# CLI
# ============================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Solar neutrino nu-e scattering plots from a flavor-separated CSV flux spectrum."
    )
    parser.add_argument(
        "csv",
        nargs="?",
        default=FLUX_DIR / "solar_neutrino_total_flux.csv",
        help="Input flux CSV from the previous solar-neutrino flux script",
    )
    parser.add_argument(
        "--outdir",
        default="solar_nu_e_plots_by_flavor",
        help="Output directory",
    )
    parser.add_argument(
        "--angular-energies",
        default="0.1,0.3,0.862,1,5,10",
        help="Comma-separated list of neutrino energies [MeV] for dσ/dcosθ plots",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    csv_path = Path(args.csv)
    outdir = Path(args.outdir)
    angular_energies = [float(x) for x in args.angular_energies.split(",") if x.strip()]

    df = read_flux_csv(csv_path)
    make_plots(df, outdir=outdir, angular_energies=angular_energies)

    print(f"Read {len(df)} valid flux points from: {csv_path}")
    print(f"Saved outputs in: {outdir.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())